### ISSUE TITLE
Gem rewriting

### ISSUE THREAD

**Issue by chaadow** [jeffreyguenther/activestorage-openstack#3]
Hi,

First of all, I'd like to thank you for your work regarding the OpenStack provider.

Our application at work use an OpenStack provider to store the assets along with the recent `ActiveStorage` plugin that was introduced in rails 5.2. I was in charge of writing a gem that wraps the `OpenStack Swift Storage` provider as a `ActiveStorage::Service`. 

I started with your gem as a baseline and added/refactored/revamped the following : 

- Complete test coverage of all the methods in the `ActiveStorage::Service` interface ( inspired from [these rails shared tests](https://github.com/rails/rails/blob/master/activestorage/test/service/shared_service_tests.rb)
- Implementation of all the methods from the  `ActiveStorage::Service` interface.
- Usage of the [request](https://github.com/fog/fog-openstack/tree/master/lib/fog/storage/openstack/requests) layer ( aka `Fog::OpenStack::Real`) over the `model` layer as advised [here](https://github.com/fog/fog-openstack/blob/master/docs/storage.md)
- Add Direct Upload support.
- Rewrite of the `#upload` method to send the etag/checksum from the request, as _strongly recommended_ [here](https://developer.openstack.org/api-ref/object-store/index.html#objects)
- Add exception handling (with OpenStack exceptions)

Here are the [tests](https://github.com/chaadow/activestorage-openstack/blob/master/test/active_storage/service/open_stack_service_test.rb) along with their [implementation](https://github.com/chaadow/activestorage-openstack/blob/master/lib/active_storage/service/open_stack_service.rb).

I heavily explored the OpenStack Swift documentation, and tried to integrate as much from the API as I could, in addition to your TODO list.

I woud like to know what are your thoughts, and thank you again for your work.
(The link again is here : https://github.com/chaadow/activestorage-openstack/)

**Comment by jeffreyguenther** [comment]
Hi! 

I'm so happy to see that someone picked up my work and took it the distance. Your gem will be a great asset to the community.

A couple observations:
* Is it possible to replace `Time.zone.now` with `Time.current`?
* I think it would be helpful in your readme to describe the steps necessary to setup a container on an OpenStack environment. Are there any tasks you need to do to grant it permissions, etc? I think having this type of guidance will make it easier for people to adopt the gem, especially those less familiar with OpenStack.

I'm going to add a note sending people to your repo.

Thanks again for finishing up this effort! 👏

**Comment by jeffreyguenther** [comment]
You can remove the note about yours being a rewrite as it is now _the_ gem. 👍 

Any feedback/improvements I have will come via issues or PRs. Thanks again!

**Comment by chaadow** [comment]
You're very welcome. I appreciate it!

I went ahead and opened an issue with your observations. I'll refine the README and restore the `Time.current` which is a safer and saner way to retrieve the current time.

Sure, your feedback is appreciated. It's been a pleasure working on the gem and I hope my contribution would benefit the Ruby/Rails community.
